# Anger by Thích Nhât Hanh {#sec-AngerBook}

Thích Nhât Hanh is a Vietnamese Zen Buddhist monk, teacher, author, and peace activist. He is known for his contributions to the development of Engaged Buddhism and his emphasis on mindfulness and compassion in daily life. Thích Nhât Hanh was born in Vietnam in 1926 and ordained as a monk at the age of 16. He has played a leading role in the Buddhist revival movement in Vietnam and has worked to bring an end to the Vietnam War. Thích Nhât Hanh is the founder of the Plum Village Community of Engaged Buddhism, a network of monasteries, practice centers, and communities in Europe and the United States. *Source: chatgpt.*

## Listening

::: {style="color: gray"}
1. "*You listen just because you want the other person to suffer less.*"
:::

::: {style="color: gray"}
2. "*You have to be very concentrated while you listen. You have to focus on the practice of listening with all your attention, your whole being: your eyes, ears, body, and your mind. If you just pretend to listen, and do not listen with one hundred percent of yourself, the other person will know it and will not find relief from his suffering. If you know how to practice mindful breathing and can stay focused on the desire to help him find relief, then you will be able to sustain your compassion while listening.*"
:::

## The Mind Body

::: {style="color: gray"}
1. "*Namarupa is the psyche-soma, the mind-body as one entity.*"
:::

::: {style="color: gray"}
2. "*If we eat well and chew our food carefully, we get more nutrition than if we eat a lot but don't digest it well.*"
:::

## The Source of Anger

::: {style="color: gray"}
1. "*In our consciousness there are blocks of pain, anger, and frustration called internal formations. They are also called knots because they tie us up and obstruct our freedom. When someone insults us, or does something unkind to us, an internal formation is created in our consciousness. If you don't know how to undo the internal knot and transform it, the knot will stay there for a long time. And the next time someone says something or does something to you of the same nature, that internal formation will grow stronger. As knots or blocks of pain in us, our internal formations have the power to push us, to dictate our behavior.*"
:::

::: {style="color: gray"}
2. "*Let us use a house to represent our consciousness. We can identify two parts: the basement is the store consciousness and the living area is mind consciousness. Internal formations, like anger, rest in the store consciousness---in the basement---in the form of a seed, until you hear, see, read, or think of something that touches your seed of anger. Then it comes up and manifests on the level of your mind consciousness, your living room. It manifests as a zone of energy that makes the atmosphere in your living room heavy and unpleasant. When the energy of anger comes up, we suffer.*"
:::

::: {style="color: gray"}
3. "*Our blocks of pain, sorrow, anger, and despair always want to come up into our mind consciousness, into our living room, because they have grown big and need our attention. They want to emerge, but we don't want them to come up because they are painful to look at. So we try to block their way. We want them to stay asleep down in the basement. Because we do not want to face them, our habit is to fill our living room with other guests. But whenever we have ten or fifteen minutes of free time, and we don't know what to do, these internal knots will come up and make a mess in the living room. To avoid this, we pick up a book, we turn on the television, we go for a drive, we do anything to keep our living room occupied. When the living room is occupied, these unpleasant internal formations will not come up.*"
:::

## Handling Anger

::: {style="color: gray"}
1. "*If your house is on fire, the most urgent thing to do is to go back and try to put out the fire, not to run after the person you believe to be the arsonist.*"
:::

::: {style="color: gray"}
2. "*You accept your anger because you know you can take care of it; you can transform it into positive energy.*"
:::

::: {style="color: gray"}
3. "*So in taking good care of yourself, you take good care of your beloved one. Self-love is the foundation for your capacity to love the other person. If you don't take good care of yourself, if you are not happy, if you are not peaceful, you cannot make the other person happy. You cannot help the other person; you cannot love. Your capacity for loving another person depends entirely on your capacity for loving yourself, for taking care of yourself.*"
:::

::: {style="color: gray"}
4. "*Your intelligence, your knowledge, does not help you change your habit energy. Only the practice of recognizing, embracing, and transforming can help. That is why the Buddha advised us to practice mindful breathing to recognize and take care of our habit energy as soon as it manifests. If you are capable of embracing your habit energy with the energy of mindfulness, then you are safe, you are not going to make the same mistake again.*"
:::

::: {style="color: gray"}
5. "*When our child is drowning in a strong emotion, we can hold his or her hand and say,"My dear one, breathe. Breathe in and out with Mommy, with Daddy." We can also invite our child to do walking meditation with us, gently taking her hand and helping her calm down, with each step. When you give your child some of your mindfulness energy, she will be able to calm down very quickly and embrace her emotions.*"
:::

## Communicating Anger

::: {style="color: gray"}
1. "*Darling, I suffer, and I want you to know it. Darling, I am doing my best. I'm trying not to blame anyone else, including you. Since we are so close to each other, since we have made a commitment to each other, I feel that I need your support and your help to get out of this state of suffering, of anger.*"
:::

::: {style="color: gray"}
2. "*As we offer this guidance, we are aware there may be things that we have not understood. There may be positive things in you that we have not seen. And there may be some wrong perception on the part of the community.*"
:::

## Transforming Anger

::: {style="color: gray"}
1. "*Anger is in us in the form of a seed. The seeds of love and compassion are also there. In our consciousness, there are many negative seeds and also many positive seeds. The practice is to avoid watering the negative seeds, and to identify and water the positive seeds every day. This is the practice of love.*"
:::

::: {style="color: gray"}
2. "*When we're angry with someone, we want to hurt them. Giving them a present changes that into wanting to make them happy. So, when you are angry with someone, send him a present. After you have sent it, you will stop being angry with him. It's very simple, and it always works.*"
:::

::: {style="color: gray"}
3. "*There are moments when we feel very grateful for the other person in our life. We deeply appreciate his or her presence. We are full of compassion, gratitude, and love. We have experienced moments like this in our life. We feel so grateful that the other person is still alive, that she is still with us, and has stood by our side during very difficult times. I would suggest that if such a moment happens again, take advantage of it. To truly profit from this time, withdraw to a place where you can be alone with yourself. Don't just go to the other person and say,"I'm grateful you are there." That is not enough. You can do this later. Right at that moment, it is better to withdraw into your room or to a quiet place, and immerse yourself in that feeling of gratitude. Then write down your feelings, your gratitude, your happiness. In half a page or one page, do your best to express yourself in writing, or record yourself on tape.*"
:::

::: {style="color: gray"}
"*If you can remind yourself that the positive elements are still present within you and the other person, you will know that it is possible to break through, so that the best things in both of you can come up and manifest again.*"
:::

## Perception

::: {style="color: gray"}
1. "*We act on the basis of wrong perceptions all the time. We should not be sure of any perception we have.*"
:::

::: {style="color: gray"}
2. "*You yourself may have created the hell inside you.*"
:::

## Mindfulness

::: {style="color: gray"}
1. "*Whenever you are not standing, sitting, or lying down, you are going. But where are you going? You have already arrived. With every step, you can arrive in the present moment, you can step into the Pure Land or into the Kingdom of God. When you are walking from one side of the room to the other, or from one building to another, be aware of the contact of your feet with the earth and be aware of the contact of the air as it enters your body. It may help you to discover how many steps you can make comfortably during an in-breath and how many during an out-breath. As you breathe in, you can say"in," and as you breathe out, you can say "out.*"
:::

::: {style="color: gray"}
2. "*To learn how to live each moment of our daily life in deep mindfulness and concentration is the practice.*"
:::

::: {style="color: gray"}
3. "*You have to be aware that your emotion is just an emotion. It comes, stays for some time, and then goes away.*"
:::

::: {style="color: gray"}
4. "*Let us bring our attention down to our belly and breathe in and out. This storm will go away, so don't be afraid.*"
:::

::: {style="color: gray"}
5. "*When you remove the embargo and the blocks of pain come up, you will have to suffer a bit. There is no way to avoid it. And that is why the Buddha said that you have to learn how to embrace this pain. It is for this reason that the practice of mindfulness is so important. You generate a strong source of energy so that you can recognize, embrace, and take care of these negative energies.*"
:::

::: {style="color: gray"}
6. "*If you see elements of garbage in you, like fear, despair, and hatred, don't panic. As a good organic gardener, a good practitioner, you can face this:"I recognize that there is garbage in me. I am going to transform this garbage into nourishing compost that can make love reappear.*"
:::

## Taking Responsibility

::: {style="color: gray"}
1. "*Don't blame everything on the other person. Recognize first that the main cause of your suffering is the seed of anger in you, and that the other person is only a secondary cause.*"
:::

::: {style="color: gray"}
2. "*Human beings are not our enemy. Our enemy is not the other person. Our enemy is the violence, ignorance, and injustice in us and in the other person. When we are armed with compassion and understanding, we fight not against other people, but against the tendency to invade, to dominate, and to exploit.*"
:::

::: {style="color: gray"}
3. "*When you judge and take sides, you act as though you are outside of the conflict. You act as though you are not the black driver who was beaten, or the four policemen. But looking deeply, you see that you are the victim of the beating, and you are also the four policemen who did the beating.*"
:::

::: {style="color: gray"}
4. "*Stopping violence is what we have to do. And we cannot stop violence unless we have the insight that what we do to the other person, we are doing to ourselves.*"
:::

::: {style="color: gray"}
5. "*The way to share your insight is to help create the conditions so that others can realize the same insight---through their own experience, not just believing what you say. This takes skillfulness and patience.*"
:::

## Connection

::: {style="color: gray"}
1. "*There is no separate self." You and your son, you and your daughter are just a continuation of many generations of ancestors. You are part of a long stream of life. Whatever your children do continues to affect you deeply---just like when they were in your womb. Whatever you do still affects your children deeply because they can never be cut off from you. Your happiness and suffering are your child's happiness and suffering and vice versa. That is why you have to invest one hundred percent of yourself in the task of restoring communication.*"
:::

::: {style="color: gray"}
2. "*Most of our suffering is born from our lack of understanding and insight that there is no separate self. The other person is you, you are the other person. If you get in touch with that truth, anger will vanish.*"
:::

::: {style="color: gray"}
3. "*Who do you think you are? You are the other person. If you get angry with your son, you are getting angry with yourself. You are wrong to think that your son is not you. Your son is you. Genetically, physiologically, scientifically, your son is your continuation. That is the real truth.*"
:::

::: {style="color: gray"}
4. "*So to help your son, make peace with yourself. Look deeply into yourself. If you want to help your mother, restore peace in yourself. Discover the insight that will allow you to help your mother. Helping yourself is the first condition for helping the other. Let go of the illusion called self. This is the essence of the practice that will free you and the other person from anger and suffering.*"
:::

## On Principles and Choices

::: {style="color: gray"}
1. "*From time to time we have to make a decision, and sometimes the decision is very difficult. We are forced to make a painful choice. But if we know what is most important to us, what we most deeply want for our life, the decision-making will become easier, and we won't have to suffer a lot.*"
:::

## Five Remembrances

::: {style="color: gray"}
1. "*I am of the nature to grow old. I cannot escape old age. - I am of the nature to have ill health. I cannot escape ill health. - I am of the nature to die. I cannot escape dying. - All that is dear to me and everyone I love are of the nature to change. There is no way to escape being separated from them. I cannot keep anything. I come here empty-handed, and I go empty-handed. - My actions are my only true belongings. I cannot escape the consequences of my actions. My actions are the ground on which I stand. Every day we have to practice like this, taking a few moments to contemplate each exercise as we follow our breathing. We practice the Five Remembrances so that the seed of fear can circulate. We must invite it up to be recognized, to be embraced. And then when it goes back down again, it becomes smaller.*"
:::









