# The Courage To Be Disliked

Ichiro Kishimi is a Japanese author and speaker, known for his work in the field of cognitive-behavioral therapy and self-help. He is the author of several books, including "The Courage to be Disliked," which is a best-seller in Japan and has been translated into many languages. He is also known for his work as a speaker, where he gives talks and workshops on topics related to cognitive-behavioral therapy and self-help. He has spoken at conferences, universities, and other events in Japan and other countries. *Source: chatgpt.*\
The following quotes are from @kishimi2018courage.

## On Confrontation

::: {style="color: gray"}
1.  "*When you are challenged to a fight, and you sense that it is a power struggle, step down from the conflict as soon as possible. Do not answer his action with a reaction. That is the only thing we can do.*"
:::

## On Parenting and Relationships

::: {style="color: gray"}
1.  "*Adlerian psychology does not recommend the noninterference approach. Noninterference is the attitude of not knowing, and not even being interested in knowing what the child is doing. Instead, it is by knowing what the child is doing that one protects him. If it's studying that is the issue, one tells the child that that is his task, and one lets him know that one is ready to assist him whenever he has the urge to study. But one must not intrude on the child's task. When no requests are being made, it does not do to meddle in things.*"
:::

::: {style="color: gray"}
2.  "*When reward is at the base of an interpersonal relationship, there's a feeling that wells up in one that says, "I gave this much, so you should give me that much back." This is a notion that is quite different from separation of tasks, of course. We must not seek reward, and we must not be tied to it.*"
:::

::: {style="color: gray"}
3.  "*You convey words of gratitude, saying thank you to this partner who has helped you with your work. You might express straightforward delight: "I'm glad." Or you could convey your thanks by saying, "That was a big help." This is an approach to encouragement that is based on horizontal relationships.*"
:::

::: {style="color: gray"}
4.  "*Being praised essentially means that one is receiving judgment from another person as "good." And the measure of what is good or bad about that act is that person's yardstick. If receiving praise is what one is after, one will have no choice but to adapt to that person's yardstick and put the brakes on one's own freedom. "Thank you," on the other hand, rather than being judgment, is a clear expression of gratitude. When one hears words of gratitude, one knows that one has made a contribution to another person.*"
:::

::: {style="color: gray"}
5.  "*They treat the idealized image as one hundred points, and they gradually subtract from that. This is truly a "judgment" way of thinking. Instead, the parents could refrain from comparing their child to anyone else, see him for who he actually is, and be glad and grateful for his being there.*"
:::

::: {style="color: gray"}
6.  "*We can live only in the here and now. Our lives exist only in moments. Adults who do not know this attempt to impose "linear" lives onto young people. Their thinking is that staying on the conventional tracks---good university, big company, stable household---is a happy life. But life is not made up of lines or anything like that.*"
:::

## On Bad Narratives

::: {style="color: gray"}
1.  "*You notice only your shortcomings because you've resolved to not start liking yourself. In order to not like yourself, you don't see your strong points and focus only on your shortcomings. First, understand this point.*"
:::

::: {style="color: gray"}
2.  "*One can think from the viewpoint that it is an interpersonal relationship card. As long as I use etiology to think, It is because he hit me that I have a bad relationship with my father, it would be a matter that was impossible for me to do anything about. But if I can think, I brought out the memory of being hit because I don't want my relationship with my father to get better, then I will be holding the card to repair relations.*"
:::

## On Making a Change

::: {style="color: gray"}
1.  "*Do not cling to the small community right in front of you. There will always be more "you and I," and more "everyone," and larger communities that exist.*"
:::

## On Finding Meaning

::: {style="color: gray"}
1.  "*It's quite simple. It is when one is able to feel "I am beneficial to the community" that one can have a true sense of one's worth.*"
:::

::: {style="color: gray"}
2.  "*If one really has a feeling of contribution, one will no longer have any need for recognition from others.*"
:::

::: {style="color: gray"}
3.  "*Because one will already have the real awareness that "I am of use to someone," without needing to go out of one's way to be acknowledged by others. In other words, a person who is obsessed with the desire for recognition does not have any community feeling yet, and has not managed to engage in self-acceptance, confidence in others, or contribution to others.*"
:::


