# The Creative Act by Rick Ruben {#sec-CreativeBook}

Rick Rubin is a well-known American record producer and music executive. He is known for his significant contributions to the music industry and has worked with numerous iconic artists across different genres.

Rick Rubin co-founded Def Jam Recordings in the 1980s and played a crucial role in the development of hip-hop music. He has also produced albums for a wide range of artists, including rock, pop, and country musicians. Some of the artists he has worked with include Beastie Boys, Run-D.M.C., Johnny Cash, Red Hot Chili Peppers, Slayer, and more. *Source: chatgpt.*

The following quotes are from @rubin2023create.

::: {style="color: gray"}
1.  "*To create is to bring something into existence that wasn't there before. It could be a conversation, the solution to a problem, a note to a friend, the rearrangement of furniture in a room, a new route home to avoid a traffic jam.*"
:::

::: {style="color: gray"}
2.  "*Practicing a way of being that allows you to see the world through uncorrupted, innocent eyes can free you to act in concert with the universe's timetable.*"
:::

::: {style="color: gray"}
3.  "*The things we believe carry a charge regardless of whether they can be proven or not.*"
:::

::: {style="color: gray"}
4.  "*We can decide to take three slow, deep breaths upon awakening each morning. This simple act can set a course to start each day still, centered, and in the moment.*"
:::

::: {style="color: gray"}
5.  "*Nature transcends our tendencies to label and classify, to reduce and limit. The natural world is unfathomably more rich, interwoven, and complicated than we are taught, and so much more mysterious and beautiful.*"
:::

::: {style="color: gray"}
6.  "*We're not playing to win, we're playing to play. And ultimately, playing is fun. Perfectionism gets in the way of fun. A more skillful goal might be to find comfort in the process. To make and put out successive works with ease.*"
:::

::: {style="color: gray"}
7.  "*We can apply this same technique to ourselves and embrace our imperfections. Whatever insecurities we have can be reframed as a guiding force in our creativity. They only become a hindrance when they prevent our ability to share what's closest to our heart.*"
:::

::: {style="color: gray"}
8.  "*An old man in Calcutta would walk to get water from a well every day. He'd carry a clay pot and lower it by hand slowly, all the way down, careful not to let it hit the sides of the well and break. Once it was full, he'd raise the pot slowly and carefully again. It was a focused, time-consuming act. One day, a traveler noticed the old man engaged in this difficult task. More experienced with mechanics, he showed the old man how to use a pulley system. "This will allow the pot to go straight down quickly," the traveler explained, "then fill with water and come back up, without hitting the sides. It's much easier and the pot will be just as full with much less work." The old man looked at him and said, "I think I'm going to keep doing it the way I always have. I really have to think about each movement and there's a great deal of care that goes into doing it right. I'd imagine if I were to use the pulley, it would become easy and I might even start thinking about something else while doing it. If I put so little care and time into it, what might the water taste like? It couldn't possibly taste as good."*"
:::

::: {style="color: gray"}
9.  "*Often, the most innovative ideas come from those who master the rules to such a degree that they can see past them or from those who never learned them at all.*"
:::

::: {style="color: gray"}
10. "*Rules obeyed unconsciously are far stronger than the ones set on purpose. And they are more likely to undermine the work.*"
:::

::: {style="color: gray"}
11. "*For every rule followed, examine the possibility that the opposite might be similarly interesting. Not necessarily better, just different. In the same way, you can try the opposite or the extreme of what's suggested in these pages and it will likely be just as fruitful.*"
:::

::: {style="color: gray"}
12. "*Formulating an opinion is not listening. Neither is preparing a response, or defending our position or attacking another's. To listen impatiently is to hear nothing at all. Listening is suspending disbelief.*"
:::

::: {style="color: gray"}
13. "*Many of our beliefs were learned before we had a choice in what we were taught. Some of them might go back generations and may no longer apply. Some may never have applied. Listening, then, is not just awareness. It's freedom from accepted limitations.*"
:::

::: {style="color: gray"}
14. "*Great art is created through freedom of self-expression and received with freedom of individual interpretation.*"
:::

::: {style="color: gray"}
15. "*If we live in a mindset of scarcity, we hoard great ideas. A comedian may be presented with a perfect opportunity to tell a favorite new joke they've written, but instead will hold it back waiting for a more high-profile occasion. When we use our material, new content comes through. And the more we share, the more our skills improve.*"
:::

::: {style="color: gray"}
16. "*Our life's work is far greater than any individual container. The works we do are at most chapters. There will always be a new chapter, and another after that. Though some might be better than others, that is not our concern. Our objective is to be free to close one chapter and move on to the next, and to continue that process for as long as it pleases us.*"
:::

::: {style="color: gray"}
17. "*Putting your best effort in at each moment, in each chapter, is all we can ever hope to accomplish.*"
:::

::: {style="color: gray"}
18. "*If you are living in the belief that success will cure your pain, when the treatment comes and doesn't work, it can lead to hopelessness. A depression can accompany the realization that what you've spent most of your life chasing hasn't fixed your insecurities and vulnerabilities. More likely, with the stakes and consequences now higher, it has only amplified the pressure. And we are never taught how to handle this epic disappointment.*"
:::

::: {style="color: gray"}
19. "*The outcome is not the outcome. The darkness is not an end point, nor is the daylight. They live in a continually unfolding, mutually dependent cycle. Neither is bad or good. They simply exist.*"
:::

::: {style="color: gray"}
20. "*Be aware of strong responses. If you're immediately turned off by an experience, it's worth examining why.*"
:::

::: {style="color: gray"}
21. "*You are creating the work that best represents you. Another artist is making the work that best represents them.*"
:::

::: {style="color: gray"}
22. "*Refine it to the point where it is stripped bare, in its least decorative form yet still intact. With nothing extra. Sometimes the ornamentation can be of use, often not. Less is generally more.*"
:::

::: {style="color: gray"}
23. "*Generally our explanations are guesses. These vague hypotheticals become fixed in our minds as fact. We are interpretation machines, and this process of labeling and detaching is efficient but not accurate. We are the unreliable narrators of our own experience.*"
:::

::: {style="color: gray"}
24. "*Working to free yourself from inner voices is a kind of meditation. Set aside all concerns for a stretch of time and say, I'm only going to focus on this one practice: making great work.*"
:::

::: {style="color: gray"}
25. "*In addition to meditation, we might softly hold on to a question and go for a walk, swim, or drive. The question isn't being worked on, just loosely held in awareness. We are posing it gently to the Universe and opening ourselves to receive an answer.*"
:::

::: {style="color: gray"}
26. "*You work not as an evangelist, expecting miracles, but as a scientist, testing and adjusting and testing again. Experimenting and building on the results. Faith is rewarded, perhaps even more than talent or ability. After all, how can we offer the art what it needs without blind trust? We are required to believe in something that doesn't exist in order to allow it to come into being.*"
:::

::: {style="color: gray"}
27. "*In the process of experimentation, we allow ourselves to make mistakes, to go too far, to go even further, to be inept. There is no failure, as every step we take is necessary to reach our destination, including the missteps. Each experiment is valuable in its own way if we learn something from it. Even if we can't comprehend its worth, we are still practicing our craft, moving ever so much closer to mastery.*"
:::

::: {style="color: gray"}
28. "*When testing, don't overintellectualize your choice of criteria. You're looking for that first instinct, the knee-jerk reaction before any thought. The instinctual tug tends to be the purest, whereas the second, more reasoned thought tends to be processed and distorted through analysis.*"
:::

::: {style="color: gray"}
29. "*The moment one collaborator gives in and settles on a less preferential option for the sake of moving forward, everyone loses. Great decisions aren't made in a spirit of sacrifice. They're made by the mutual recognition of the best solution available.*"
:::
