# Lectures and Saying by Musonius Rufus {#sec-SayingsBook}

Musonius Rufus (c. 30-100 AD) was a Roman Stoic philosopher. He was known for his teachings on ethics, virtue, and the principles of Stoicism. Musonius Rufus was a prominent figure in the Stoic school and had a significant influence on his contemporaries and later Stoic philosophers. *Source: chatgpt.*

The following quotes are from @king2011sayings.

::: {style="color: gray"}
1.  "*And yet, wouldn't everyone agree that it is much better to work to gain control over one's own desires than it is to work to gain possession of someone else's wife---and for a person to train himself to want little instead of struggling to become wealthy? And instead of exerting effort to gain fame, shouldn't a person strive to overcome his thirst for it? Instead of searching for a way to damage a person whom he envies, shouldn't he contemplate how not to bear envy against anyone? Instead of being slavish to some so-called friends, who are actually insincere, shouldn't he make sacrifices to win true friends?*"
:::

::: {style="color: gray"}
2.  "*you are a good and virtuous person, exile would not harm or diminish you, because you still have the things that can best assist and elevate you.*"
:::

::: {style="color: gray"}
3.  "*A beast is not able to comprehend that many of the wrongs done to people are done out of ignorance and a lack of understanding. A person who gains this comprehension immediately stops doing wrong.*"
:::

::: {style="color: gray"}
4.  "*And, indeed, at each meal, there is not one chance for making a mistake, but several. The person who eats more than he should makes a mistake. So does the person who eats in a hurry, the person who is enthralled by gourmet food, the person who favors sweets over nutritious foods, and the person who does not share his food equally with his fellow-diners. We make another mistake in connection with food when we leave what we are supposed to be doing in order to eat, even though it isn't mealtime.*"
:::

::: {style="color: gray"}
5.  "*is not possible to live well today unless you treat it as your last day.*"
:::

::: {style="color: gray"}
6.  "*The treasures of Croesus and Cinyras we shall consider equivalent to extreme poverty. Indeed, we will hold that one man and one man only is truly wealthy---he who learns to want nothing in every circumstance.*"
:::

::: {style="color: gray"}
7.  "*"Consider this. If you have accomplished something good through hard work, that labor will quickly disappear. If something is done well by you, it will not disappear as long as you live. But if you have done something wicked in the pursuit of pleasure, the pleasure will quickly disappear, but the wicked thing will stay with you forever."*"
:::
