# The Cosmic Serpent by Jeremy Narby {#sec-SerpentBook}

Jeremy Narby is a Swiss-Canadian anthropologist and author known for his work on indigenous knowledge, shamanism, and the relationship between traditional wisdom and modern science. Narby's work has led to discussions about the intersection of indigenous wisdom, scientific inquiry, and the nature of consciousness. His ideas have influenced dialogues around the relationships between traditional cultures and Western scientific approaches. *Source: chatgpt.*

The following quotes are from @narby1999serpent.

::: {style="color: gray"}
1.  "*I was continually struck by their profound practicality. They did not talk of doing things; they did them.*"
:::

::: {style="color: gray"}
2.  "*I am just a human being, for example, and am intimately linked to other life forms and that true reality is more complex than our eyes lead us to believe.*"
:::

::: {style="color: gray"}
3.  "*What if it were true that nature speaks in signs and that the secret to understanding its language consists in noticing similarities in shape or in form?*"
:::

::: {style="color: gray"}
4.  "*“to objectify one’s objectifying relationship,” which is another way of saying “to become aware of one’s gaze.”*"
:::

::: {style="color: gray"}
5.  "*Nigerian scam artist once told The New York Times that he felt guilty for hurting others, but “poverty will not make you feel the pain.*"
:::

::: {style="color: gray"}
6.  "*it was by going back and forth between these two levels that one could bring back useful and verifiable knowledge that was otherwise unobtainable.*"
:::

::: {style="color: gray"}
7.  "*Popper proposed instead to test theories in ways that seek to contradict, or falsify, them; the absence of contradictory evidence thereby becomes proof of the theory’s validity.*"
:::
