# Siddhartha by Hermann Hesse

Hermann Hesse was a German-Swiss poet, novelist, and painter. He is best known for his novels "Steppenwolf", "Siddhartha", and "The Glass Bead Game," which explore themes of individual spiritual journeys, and the search for authenticity and self-knowledge. He was awarded the Nobel Prize in Literature in 1946. *Source: chatgpt.*
The following quotes are from @hesse1922sidd.

## On Change

::: {style="color: gray"}
1.  "*I am travelling. I was a rich man and am no rich man any more, and what I'll be tomorrow, I don't know.*"
:::

::: {style="color: gray"}
2.  "*Where is Siddhartha the Brahman? Where is Siddhartha the Samana? Where is Siddhartha the rich man? Non-eternal things change quickly, Govinda, you know it.*"
:::

## On Learning and Knowing

::: {style="color: gray"}
1.  "*to get a taste of everything for oneself, which one needs to know. That lust for the world and riches do not belong to the good things, I have already learned as a child. I have known it for a long time, but I have experienced only now. And now I know it, don't just know it in my memory, but in my eyes, in my heart, in my stomach. Good for me, to know this!*"
:::

## On Parenting

::: {style="color: gray"}
1.  "*You don't force him, don't beat him, don't give him orders, because you know that 'soft' is stronger than 'hard', Water stronger than rocks, love stronger than force. Very good, I praise you. But aren't you mistaken in thinking that you wouldn't force him, wouldn't punish him? Don't you shackle him with your love? Don't you make him feel inferior every day, and don't you make it even harder on him with your kindness and patience? Don't you force him, the arrogant and pampered boy, to live in a hut with two old banana-eaters, to whom even rice is a delicacy, whose thoughts can't be his, whose hearts are old and quiet and beats in a different pace than his? Isn't forced, isn't he punished by all this?*"
:::

::: {style="color: gray"}
2.  "*Would you actually believe that you had committed your foolish acts in order to spare your son from committing them too?*"
:::

::: {style="color: gray"}
3.  "*Which father, which teacher had been able to protect him from living his life for himself, from soiling himself with life, from burdening himself with guilt, from drinking the bitter drink for himself, from finding his path for himself?*"
:::

## On Flowing

::: {style="color: gray"}
1.  "*In this hour, Siddhartha stopped fighting his fate, stopped suffering. On his face flourished the cheerfulness of a knowledge, which is no longer opposed by any will, which knows perfection, which is in agreement with the flow of events, with the current of life, full of sympathy for the pain of others, full of sympathy for the pleasure of others, devoted to the flow, belonging to the oneness.*"
:::

::: {style="color: gray"}
2.  "*When someone is searching,” said Siddhartha, “then it might easily happen that the only thing his eyes still see is that what he searches for, that he is unable to find anything, to let anything enter his mind, because he always thinks of nothing but the object of his search, because he has a goal, because he is obsessed by the goal. Searching means: having a goal. But finding means: being free, being open, having no goal. You, oh venerable one, are perhaps indeed a searcher, because, striving for your goal, there are many things you don't see, which are directly in front of your eyes.” I*"
:::
