# The Science of Story Telling by Will Storr

In a stable environment, the brain is relatively calm. But when it detects change, that event is immediately registered as a surge of neural activity.
Control is why brains are on constant alert for the unexpected. Unexpected change is a portal through which danger arrives to swipe at our throats.
‘There’s no terror in the bang, only in the anticipation of it.’
‘There is a natural inclination to resolve information gaps,’ wrote Loewenstein, ‘even for questions of no importance.’
There is, concluded Loewenstein, a ‘positive relationship between curiosity and knowledge’. The more context we learn about a mystery, the more anxious we become to solve it.
four ways of involuntarily inducing curiosity in humans: (1) the ‘posing of a question or presentation of a puzzle’; (2) ‘exposure to a sequence of events with an anticipated but unknown resolution’; (3) ‘the violation of expectations that triggers a search for an explanation’; (4) knowledge of ‘possession of information by someone else’.
‘Evolution shaped us with perceptions that allow us to survive,’ the cognitive scientist Professor Donald Hoffman has said. ‘But part of that involves hiding from us the stuff we don’t need to know. And that’s pretty much all of reality, whatever reality might be.’
Brains take information from the outside world – in whatever form they can – and turn it into models.
A wolf survives by cooperating as well as fighting for dominance and killing prey. A dog does so by manipulating its human owner such that they’d do anything for them.
The novelist and psychologist Professor Charles Fernyhough has led research in which 19 per cent of readers reported hearing the voices of fictional characters even after they’d put their books down. Some reported a kind of literary possession, with the character influencing the tone and nature of their thoughts.
When our attention rests upon a glass of red wine, say, a large number of neurons in different parts of the brain are simultaneously activated. We don’t have a specific ‘glass of wine’ area that lights up, what we have are responses to ‘liquid’, ‘red’, ‘shiny surface’, ‘transparent surface’, and so on. When enough of these are triggered, the brain understands what’s in front of it and constructs the glass of wine for us to ‘see’.
The further you travel from those you admire, the more wrong people become until the only conclusion you’re left with is that entire tranches of the human population are stupid, evil or insane. Which leaves you, the single living human who’s right about everything – the perfect point of light, clarity and genius who burns with godlike luminescence at the centre of the universe.
After all, hadn’t his model of reality and its theory of control worked? Hadn’t his belief in the sacred value of emotional restraint given him his career, his status and protected him from the pain of losing his father? Ishiguro’s novel is an exploration of the truth of that flaw and its ramifications – how, as Salman Rushdie has written, Stevens was, ‘destroyed by the ideas upon which he has built his life’.
When designing a character, it’s often useful to think of them in terms of their theory of control. How have they learned to control the world?
For Westerners, reality is made up of individual pieces and parts. When threatening unexpected change strikes, we tend to reimpose control by going to war with those pieces and parts and trying to tame them. For Easterners, reality is a field of interconnected forces. When threatening unexpected change strikes, they’re more likely to reimpose control by attempting to understand how to bring those turbulent forces back into harmony so that they can all exist together. What they have in common is story’s deepest purpose. They are lessons in control.
‘Once [the brain’s] internal structures are established they turn the relationship between the internal and external around. Instead of the internal structures being shaped by the environment, the individual now acts to preserve established structures in the face of environmental challenges, and finds changes in structure difficult and painful.’
It’s not simply that we ignore or forget evidence that goes against what our models tell us (although we do that too). We find dubious ways of rejecting the authority of opposing experts, give arbitrary weight to some parts of their testimony and not others, lock onto the tiniest genuine flaws in their argument and use them to dismiss them entirely. Intelligence isn’t effective at dissolving these cognitive mirages of rightness. Smart people are mostly better at finding ways to ‘prove’ they’re right and tend to be no better at detecting their wrongness.
The rational response, when encountering someone with alien ideas, would be to either attempt to understand them or shrug. And yet we become distressed. Our threatened neural models generate waves of sometimes overwhelming negative feelings. Incredibly, the brain treats threats to our neural models in the much same way as it defends our bodies from a physical attack, putting us into a tense and stressful fight-or-flight state. The person with merely differing views becomes a dangerous antagonist, a force that’s actively attempting to harm us. The neuroscientist Professor Sarah Gimbel watched what happened when people in brain scanners were presented with evidence their strongly held political beliefs were wrong. ‘The response in the brain that we see is very similar to what would happen if, say, you were walking through the forest and came across a bear,’ she has said.
Researchers have found that violence and cruelty has four general causes: greed and ambition; sadism; high self-esteem and moral idealism. Popular belief and clichéd stories tend to have it that greed and sadism are dominant. In fact, they’re vanishingly small. It’s actually high self-esteem and moral idealism – convictions of personal and moral superiority – that drive most acts of evil.
‘You talk about the people as if you owned them, as though they belonged to you,’ he says, slurring slightly. ‘Goodness. As long as I can remember you’ve talked about giving the people their rights, as if you could make them a present of liberty. As a reward for services rendered. Remember the working man? You used to write an awful lot about the working man. But he’s turning to something called organised labour. You’re not going to like that one little bit when you find out it means that your working man expects something as his right, not as your gift. When your precious underprivileged really get together
The terrible and fascinating truth about the human condition is that none of us really know the answer to the dramatic question as it pertains to ourselves. We don’t know why we do what we do, or feel what we feel. We confabulate when theorising as to why we’re depressed, we confabulate when justifying our moral convictions and we confabulate when explaining why a piece of music moves us. Our sense of self is organised by an unreliable narrator. We’re led to believe we’re in complete control of ourselves, but we’re not. We’re led to believe we really know who we are, but we don’t.
Michael Gazzaniga
individuals are essentially scientists erecting and testing their hypotheses about the world and revising them in the light of their experience.
We believe we’re in control of ourselves but we’re continually being altered by the world and people around us. The difference is that in life, unlike in story, the dramatic question of who we are never has a final and truly satisfying answer.
When people in brain scanners read of another’s wealth, popularity, good looks and qualifications, regions involved in the perception of pain became activated. When they read about them suffering a misfortune, they enjoyed a pleasurable spike in their brain’s reward systems.
All of us are being silently controlled by any number of instructional stories at once.
Tribal stories blind us. They allow us to see only half the truth, at best.
Keeping the secret of ourselves from ourselves can be exhausting. This, perhaps, is the subversive truth of stories about antiheroes. Being freed to be evil, if only in our minds, can be such a joyful relief.
Because humans crave control, infants whose caregivers behave unpredictably can grow up in a constant state of anxious high alert. Their distress gets built into their core concepts about people which can lead to significant social problems when they’re grown.
The psychologists Professors John Bransford and Marcia Johnson asked people to remember the following passage:
‘We are our personal projects.’
“Stop hoping for happiness tomorrow. Happiness is being engaged in the process.”’
‘The transformation that narrative transportation achieves is persuasion of the story-receiver.’
The magic of story is its ability to connect mind with mind in a manner that’s unrivalled even by love. Story’s gift is the hope that we might not be quite so alone, in that dark bone vault, after all.
