# From Strength to Strength by Arthur C. Brooks

Arthur C. Brooks is an American social scientist, author, and public commentator. He has held various positions related to economics, public policy, and social issues. He is known for his research on topics such as economic opportunity, happiness, and the intersection of economics and culture.

Brooks has also been associated with think tanks and policy organizations. He served as the president of the American Enterprise Institute (AEI), a conservative think tank, from 2009 to 2019. During his tenure at AEI, he focused on promoting ideas related to free enterprise, individual liberty, and economic growth. *Source: chatgpt.*

The following quotes are from @brooks2022strength.

## Quotes

::: {style="color: gray"}
1.  "*Here is the reality: in practically every high-skill profession, decline sets in sometime between one’s late thirties and early fifties. Sorry, I know that stings. And it gets worse: the more accomplished one is at the peak of one’s career, the more pronounced decline seems once it has set in.*"
:::

::: {style="color: gray"}
2.  "*The researchers found that physicians over sixty-five are 50 percent more likely than younger doctors (under fifty-one) at being found at fault for malpractice.*"
:::

::: {style="color: gray"}
3.  "*We might call this the “principle of psychoprofessional gravitation”: the idea that the agony of decline is directly related to prestige previously achieved, and to one’s emotional attachment to that prestige.*"
:::

::: {style="color: gray"}
4.  "*The first is fluid intelligence, which Cattell defined as the ability to reason, think flexibly, and solve novel problems. Fluid intelligence isn’t the only kind—there is also crystallized intelligence. This is defined as the ability to use a stock of knowledge learned in the past.*"
:::

::: {style="color: gray"}
5.  "*every change of circumstances is a chance to learn, grow, and create value.*"
:::

::: {style="color: gray"}
6.  "*...work, which is a source of meaning and purpose, becomes workaholism, which hurts our relationships. Success, the fruit of excellence, becomes an addiction. All because of pride. In fact, perfectionism and the fear of failure go hand in hand: they lead you to believe that success isn’t about doing something good but about not doing something bad.*"
:::

::: {style="color: gray"}
7.  "*The point is that the symbols of your specialness have encrusted you like a ton of barnacles. Not only are these things incapable of bringing you any real satisfaction; they’re making you too heavy to jump to your next curve.*"
:::

::: {style="color: gray"}
8.  "*In the East, we believe the art already exists, and our job is simply to reveal it. It is not visible because we add something, but because we take away the parts that are not the art.*"
:::

::: {style="color: gray"}
9.  "*I shall overcome with the simplicity of original nature. With the simplicity of true nature, there shall be no desire. Without desire, one’s original nature will be at peace. And the world will naturally be in accord with the right Way.*"
:::

::: {style="color: gray"}
10.  "*He has most who needs least. Don’t create needs for yourself.*"
:::

::: {style="color: gray"}
11.  "*To begin depriving death of its greatest advantage over us, let us deprive death of its strangeness, let us frequent it, let us get used to it; let us have nothing more often in mind than death.*"
:::

::: {style="color: gray"}
12.  "*Solitude expresses the glory of being alone, whereas loneliness expresses the pain of feeling alone.*"
:::

::: {style="color: gray"}
13.  "*Many have written about the so-called “gratitude walk,” the practice of focusing on the positive events in your life while walking, helping you to savor happiness by amplifying gratitude.*"
:::

::: {style="color: gray"}
14.  "*...it was through my weakness, not my strength, that I was able to connect with people I never would have met otherwise. Elite credentials don’t make you relatable. They are a barrier to deep human connection.*"
:::

::: {style="color: gray"}
15.  "*sadness has persisted in the face of evolution because it brings cognitive benefits. There is evidence that it makes us better at assessing reality in social situations, because we are less likely to flatter ourselves or gloss over negative truths. Sadness can even make us more productive at work by enhancing focus and helping us learn from mistakes. This is how failure, via the resulting negative emotions, can help lead to later success.*"
:::

::: {style="color: gray"}
16.  "*Research shows that stress inoculation training—in which people learn to cope with anger, fear, and anxiety by being exposed to stimuli that cause these feelings—is effective in creating emotional resilience. It is easy to imagine that attempts to eliminate pain and weakness from daily life could lead to a sort of emotional allergy—that when hard times come and someone feels grief or fear that is impossible to ignore, that person will not have the tools to face these feelings.*"
:::

